version: "3.7"

services:
  vehicle-detection-api:
    container_name: "vehicle-detection-api"
    image: vehicle-detection-api:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${HOST_IMAGES_PATH}:/root/app/images
    env_file:
      - ./config/vehicle-detection.env

  db:
    container_name: "db"
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    env_file:
      - ./config/db.env
