version: "3.7"

services:
  vehicle-detection-api:
    container_name: "vehicle-detection-api"
    image: vehicle-detection-api:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${HOST_IMAGES_PATH}:/root/app/images
    env_file:
      - ./config/vehicle-detection.env

  backend-db:
    container_name: "backend-db"
    image: backend-db:latest
    restart: always
    ports:
      - 5000:5000

  db:
    container_name: "db"
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    env_file:
      - ./config/db.env

  broker:
    image: eclipse-mosquitto:2.0.11
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./logs/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
      - 1883:1883

  mqtt_microservice:
    build: ./mqtt_microservice
    restart: always
    environment:
      MQTT_URL: mqtt://broker:1883
      MQTT_TOPIC: proximity_sensor
    depends_on:
      - broker
    volumes:
      - ./mqtt_microservice/mqtt_bridge.js:/usr/src/mqtt_bridge.js
    command: npx nodemon -L mqtt_bridge.js

  backend-photo:
    build: ./splot_backend
    environment:
      TEST: "asd"
    volumes:
      - ./images:/usr/src/images
      - ./splot_backend/index.js:/usr/src/index.js
      - ./config/cameras-ip.json:/usr/src/config/cameras-ip.json
    ports:
      - 3000:3000
    command: npx nodemon -L index.js
